# Generated by Django 5.0.1 on 2024-03-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='Store.basket'),
        ),
    ]
